#! /bin/sh

xsetroot -cursor_name left_ptr &

sxhkd &

if [ $(hostname) = judgement ]
then
	if glxinfo | egrep -iq 'direct rendering: yes'; then
		EXECOMP='compton --vsync opengl'
	else
		EXECOMP='compton'
	fi
	$EXECOMP &
else
	compton &
fi

nitrogen --restore &

tint2 &

pnmixer &
[ $(hostname) = judgement ] && xfce4-power-manager &

thunar --deamon &

setxkbmap us altgr-intl &
xset b 100&
xset mouse 1 1 &
numlockx on &

#[ ! -s ~/.mpd/pid ] && mpd &

fcitx-autostart &

parcellite &

if [ $(hostname) = judgement ]
then
	bspc wm -O DP-0 HDMI-0
	bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
	bspc monitor HDMI-0 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
else
	bspc monitor DP-2 -d I II III IV V VI VII VIII IX X
	bspc monitor DP-0 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
fi

bspc config border_width         2
#bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config click_to_focus       true
#bspc config top_padding          25

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
