#! /bin/sh

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

xsetroot -cursor_name left_ptr &

nitrogen --restore &

[ $(hostname) = judgement ] && xfce4-power-manager &

setxkbmap -layout us -variant euro -option compose:ralt &
xset b 100 &
xset mouse 1 1 &
numlockx on &

bspswallow &

if [ $(hostname) = judgement ]
then
	bspc wm -O DP-0 HDMI-0
	bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
	bspc monitor HDMI-0 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
else
	bspc monitor ^1 -d I II III IV V VI VII VIII IX X
	bspc monitor ^2 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
fi

bspc config border_width         2
#bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config click_to_focus       true
#bspc config top_padding          25

bspc config initial_polarity second_child # Spawn windows on the right side

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a tint2 layer=below

RATE=$(echo '1000 /' $(xrandr -q | sed -nr "s/(.*\b)([0-9]+\.[0-9]+)(\*?\+)(.*)/\2/p" | sort -n | tail -1) | bc -l | xargs printf '%.f\n')
bspc config pointer_motion_interval $RATE

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

#find ~/.config/systemd/user -maxdepth 1 -type f | xargs -n 1 basename | xargs systemctl --user start

exec systemctl --user start bspwm-session.service
