#! /bin/sh

xsetroot -cursor_name left_ptr &

sxhkd &

tint2 &

pnmixer &

setxkbmap -layout us -variant euro -option compose:ralt &
xset b 100 &
xset mouse 1 1 &
numlockx on &

fcitx-autostart &

parcellite &

bspc monitor ^1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
#bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config click_to_focus       true
#bspc config top_padding          25

bspc config initial_polarity second_child # Spawn windows on the right side

bspc rule -a tint2 layer=below

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
